### ISSUE TITLE
Link to https://app.eurofurence.org on "Latest announcements" screen isn't clickable

### ISSUE THREAD

**Issue by sschwarzer** [eurofurence/ef-app_android#119]
Upon start of the app, there appears a page "Latest announcements" with a heading "Found a bug? Need help? Got questions?". Further down in this section is a link to https://app.eurofurence.org , which isn't clickable.

**Comment by Requinard** [comment]
The announcements that are incoming are coming in as plaintext. For now I'll take a look at https://stackoverflow.com/questions/2734270/how-do-i-make-links-in-a-textview-clickable to fix this

Due to the fact that links are usually not appearing here, this'll be on the backburner if I can't get it fixed instantly.
